### ISSUE TITLE
Hero image not loading on Home page

### ISSUE THREAD

**Issue by vi-one** [chrisrhymes/bulma-clean-theme#102]
So, I changed the theme and hero image as follows and deployed:

app.scss =>
```js
$primary: #044592;
// Import Main CSS file from theme
@import "main";
```

_config.yml =>
```yml
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      hero_image: ../img/hero.png
```

The hero image is loaded on all the pages but Home.
The apparent reason is, the requested URL to the hero image post-publish is:
`https://github-pages.cloud.capitalone.com/org/repo/img/hero.png` ✅ non-Home page.
`https://github-pages.cloud.capitalone.com/org/img/hero.png` 🚫  Home page.

Why would that be so?
