### ISSUE TITLE
Menubar (and Regular) TOC Not Displaying Title

### ISSUE THREAD

**Issue by datallurgy** [chrisrhymes/bulma-clean-theme#112]
Using the following front-matter, the TOC title is not displaying.

```yaml
---
title: Resources
subtitle: Commonly Used and Invaluable Things
layout: page
menubar_toc: true
toc_title: Things and Stuff
hide_hero: true
show_sidebar: false
---
```

I've verified my files against allejo/jekyll-toc but can't seem to find the issue.

![image](https://user-images.githubusercontent.com/94504640/151687563-4fcc48d1-1855-48d7-9acc-b8e2f40f8d04.png)
