### ISSUE TITLE
successful build and deploy from a subfolder with Github Actions workflow

### ISSUE THREAD

**Issue by HoffiMuc** [chrisrhymes/bulma-clean-theme#137]
Hi, after 2h of fiddeling around I succeded to use Github Actions workflow to build and deploy (in this case jekyll github pages theme 'bulma-clean-theme") using Github Actions workflow:

![image](https://github.com/chrisrhymes/bulma-clean-theme/assets/3447236/74d7ddc0-c33a-479c-9a4a-8daa210e40f5)

<br/>
<br/>
Maybe this might help others that run into the same "problems":

`jekyll new docs` # so the `<REPOROOT>/docs/` folder is the folder of you repo you wanna use for jekyll

in `docs/_config.yaml`
```yaml
baseurl: "/<yourGithubProjectName>" # for github pages
#baseurl: "" # for local testing
```
```yaml
# Build settings
#theme: bulma-clean-theme # for local testing
remote_theme: chrisrhymes/bulma-clean-theme # for github pages
```
```yaml
plugins:
  - jekyll-feed
  - jekyll-remote-theme
```

in `.github/workflows/jekyll-gh-pages.yml`: (add `docs/` to source: and leave destination as is)
```yaml
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site
```

in `docs/Gemfile`
```yaml
# gem "minima", "~> 2.5"
gem "bulma-clean-theme", "~> 0.13"
```

BEWARE: of prefixing all your relative links, e.g.:

```
[subpage1]({{ site.baseurl }}{% link subpage1.md %})
```

that's it.
