### ISSUE TITLE
Theme ignored after upgrading to v1

### ISSUE THREAD

**Issue by donkirkby** [chrisrhymes/bulma-clean-theme#151]
I've been using your theme for a few years, and I really like it. Thanks for publishing it.

Unfortunately, it seems to have broken for me after your recent changes upgrading to v1. When I push to my repository, the deployment to GitHub pages fails.

I tried to follow your instructions to upgrade, and I got it to deploy the site, but now it seems to have no theme at all!

Here's my `config.yml`:
```
remote_theme: chrisrhymes/bulma-clean-theme
title: Book Blender
google_analytics: UA-4644630-2
baseurl: /book-blender

defaults:
  - scope:
      path: ""
    values:
      hero_image: /book-blender/images/index_hero.jpg
      hero_darken: true
      twitter:
        card: summary_large_image
      image: images/index_hero.jpg
```

Here's my Gemfile:
```
source 'https://rubygems.org'
gem 'jekyll'
```

You can see the project at [`donkirkby/book-blender`].

I thought maybe I shouldn't be using it as a remote theme but as a gem theme, but that didn't show up either.

It's unfortunate that this breaks projects. Is there a way for projects to continue using the old version until they want to upgrade? Is there a way to learn about upcoming changes to your theme?

Let me know if I can help with documentation or some coding. I contributed a few small patches back in 2020.

[`donkirkby/book-blender`]: https://github.com/donkirkby/book-blender/tree/main/docs
