### ISSUE TITLE
Customize font style and footer

### ISSUE THREAD

**Issue by Scottdyt** [chrisrhymes/bulma-clean-theme#29]
Hey!
This is a great and powerful theme!  However, I have two problems when I use the theme:

1. I customize my own `font-face`  in `/assets/css/app.scss`, and it works for `font-family`. However, no matter how I change the `font-weight`, the result could be the same. Here are my codes:

```scss
/* Web Fonts */
/* monda-regular - latin */
@font-face {
    font-family: 'Monda';
    font-style: normal;
    font-weight: 400;
    src: local('Monda Regular'), local('Monda-Regular'),
         url('/fonts/monda-v7-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
         url('/fonts/monda-v7-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
  }
  /* monda-700 - latin */
  @font-face {
    font-family: 'Monda';
    font-style: normal;
    font-weight: 700;
    src: local('Monda Bold'), local('Monda-Bold'),
         url('/fonts/monda-v7-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
         url('/fonts/monda-v7-latin-700.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
  }
  /* julius-sans-one-regular - latin */
  @font-face {
    font-family: 'Julius Sans One';
    font-style: normal;
    font-weight: 400;
    src: local('Julius Sans One'), local('JuliusSansOne-Regular'),
         url('/fonts/julius-sans-one-v6-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
         url('/fonts/julius-sans-one-v6-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
  }
  
  body {
    font-family: 'Monda', Sans-Serif;
  }
  h1, h2, h3, h4, h5 {
    font-family: 'Julius Sans One', Sans-Serif;
  }
```

2. My homepage is very simple(less than  one page of screen), and I want to make the `footer` at **the end of screen**, what is the best way to do that?

<img width="683" alt="Screen Shot" src="https://user-images.githubusercontent.com/33884966/69614038-780fc300-106d-11ea-8434-14e052d633b3.png">

I am a css/bulma newbie, hope to get some advice, thank you!
