### ISSUE TITLE
Can I use URLs in callouts?

### ISSUE THREAD

**Issue by alewarne** [chrisrhymes/bulma-clean-theme#48]
I recently tried to put a URL in a callout like this:
```
style: is-light
height: is-medium
items:
  - title: Example callout 1
    subtitle: Example subtitle 1
    icon: fa-github
    icon_brand: true
    description: >
      The example description text goes here and can be multiple lines.

      For example, such as this. 
    call_to_action_name: Call to action 1
    call_to_action_link: https://www.google.com
```

On the generated html file, however, the "call_to_action_link" is always used relative to the folder structure of the project. Is there a way to circumvent this?

**Comment by alewarne** [comment]
I recently tried to put a URL in a callout like this:
```
style: is-light
height: is-medium
items:
  - title: Example callout 1
    subtitle: Example subtitle 1
    icon: fa-github
    icon_brand: true
    description: >
      The example description text goes here and can be multiple lines.

      For example, such as this. 
    call_to_action_name: Call to action 1
    call_to_action_link: https://www.google.com
```

On the generated html file, however, the "call_to_action_link" is always used relative to the folder structure of the project. Is there a way to circumvent this?
